
build:
  stage: build
  before_script:
    - apt update && apt install -y fontforge-nox make
    - mkdir dist
  script:
    - make truetype
    - make unifontobj
  artifacts:
    paths:
      - dist/

