
name: Proses pembuatan font TTF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Instal aplikasi FontForge dan penunjang lainnya
        run: sudo apt update && sudo apt install -y fontforge-nox make

      - name: Siapkan folder untuk menampung berkas TTF
        run: mkdir dist

      - name: Buat font TTF untuk varian tegak
        run: make truetype

      - name: Buat font TTF untuk varian serong
        run: make unifontobj

      - name: Unggah hasilnya sebagai artefak
        uses: actions/upload-artifact@v7.0.1
        with:
          path: dist/
